import { IconType } from "react-icons";
import {
  SiApachemaven,
  SiBuymeacoffee,
  SiCloudflare,
  SiCoursera,
  SiCplusplus,
  SiFlask,
  SiHibernate,
  SiIntellijidea,
  SiJavascript,
  SiLabview,
  SiMysql,
  SiOpenai,
  SiPostgresql,
  SiPostman,
  SiSpringboot,
  SiTensorflow,
  SiTypescript,
  SiVaadin,
  SiVercel,
} from "react-icons/si";

import {
  HiChevronUp,
  HiChevronDown,
  HiChevronRight,
  HiChevronLeft,
  HiArrowUpRight,
  HiOutlineArrowPath,
  HiCheck,
  HiMiniQuestionMarkCircle,
  HiMiniXMark,
  HiOutlineLink,
  HiExclamationTriangle,
  HiInformationCircle,
  HiExclamationCircle,
  HiCheckCircle,
  HiMiniGlobeAsiaAustralia,
  HiArrowTopRightOnSquare,
  HiEnvelope,
  HiCalendarDays,
  HiClipboard,
  HiArrowRight,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiMoon,
  HiOutlineMoon,
  HiMiniArrowUp,
} from "react-icons/hi2";

import {
  PiHouseDuotone,
  PiUserCircleDuotone,
  PiGridFourDuotone,
  PiBookBookmarkDuotone,
  PiImageDuotone,
} from "react-icons/pi";

import {
  FaDiscord,
  FaDownload,
  FaGithub,
  FaInstagram,
  FaJava,
  FaLinkedin,
  FaMessage,
  FaPython,
  FaQuoteLeft,
  FaQuoteRight,
  FaXTwitter,
} from "react-icons/fa6";
import {
  DiDocker,
  DiEclipse,
  DiGit,
  DiJira,
  DiMsqlServer,
} from "react-icons/di";
import { VscAzure, VscAzureDevops, VscCode } from "react-icons/vsc";
import { FiBox } from "react-icons/fi";
import { CodingSchoolIcon, IELTSIcon } from "@/components/Icons";
import { arrow } from "@floating-ui/react-dom";
import { ImLab } from "react-icons/im";
import { FcFlashOff, FcFlashOn } from "react-icons/fc";
export const iconLibrary: Record<string, IconType> = {
  chevronUp: HiChevronUp,
  chevronDown: HiChevronDown,
  chevronRight: HiChevronRight,
  chevronLeft: HiChevronLeft,
  refresh: HiOutlineArrowPath,
  arrowUpRight: HiArrowUpRight,
  check: HiCheck,
  arrowRight: HiArrowRight,
  helpCircle: HiMiniQuestionMarkCircle,
  infoCircle: HiInformationCircle,
  warningTriangle: HiExclamationTriangle,
  errorCircle: HiExclamationCircle,
  checkCircle: HiCheckCircle,
  email: HiEnvelope,
  work: FiBox,
  globe: HiMiniGlobeAsiaAustralia,
  person: PiUserCircleDuotone,
  grid: PiGridFourDuotone,
  book: PiBookBookmarkDuotone,
  close: HiMiniXMark,
  openLink: HiOutlineLink,
  calendar: HiCalendarDays,
  home: PiHouseDuotone,
  gallery: PiImageDuotone,
  discord: FaDiscord,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  github: FaGithub,
  linkedin: FaLinkedin,
  x: FaXTwitter,
  clipboard: HiClipboard,
  arrowUpRightFromSquare: HiArrowTopRightOnSquare,
  instagram: FaInstagram,
  light: HiOutlineMoon,
  dark: HiMoon,
  endQuote: FaQuoteRight,
  startQuote: FaQuoteLeft,
  javaIcon: FaJava,
  pythonIcon: FaPython,
  cIcon: SiCplusplus,
  javaScriptIcon: SiJavascript,
  typeScriptIcon: SiTypescript,
  springBootIcon: SiSpringboot,
  hibernateIcon: SiHibernate,
  mavenIcon: SiApachemaven,
  vaadinIcon: SiVaadin,
  mysqlIcon: SiMysql,
  postgresIcon: SiPostgresql,
  sqlServerIcon: DiMsqlServer,
  flaskIcon: SiFlask,
  tensorflowIcon: SiTensorflow,
  gitIcon: DiGit,
  dockerIcon: DiDocker,
  azureIcon: VscAzure,
  intellijIcon: SiIntellijidea,
  postmanIcon: SiPostman,
  vscodeIcon: VscCode,
  eclipseIcon: DiEclipse,
  azureDevopsIcon: VscAzureDevops,
  openaiIcon: SiOpenai,
  jiraIcon: DiJira,
  vercelIcon: SiVercel,
  cloudflareIcon: SiCloudflare,
  ieltsIcon: IELTSIcon,
  codingSchoolIcon: CodingSchoolIcon,
  courseraIcon: SiCoursera,
  downloadIcon: FaDownload,
  arrowUp: HiMiniArrowUp,
  mail: HiEnvelope,
  message: FaMessage,
  buyMeACoffee: SiBuymeacoffee,
  lab: ImLab,
  statusOn: FcFlashOn,
  statusOff: FcFlashOff,
};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;